### PR TITLE
feat: porting to new aegir

### PR DESCRIPTION
**Pull request by dryajov**

### CODE REVIEW

**Comment by dryajov** [comment]
@diasdavid you want me to test this against js-ipfs or ipfs-api? (I'll do both either way, just wanted to make sure)

**Comment by dryajov** [comment]
@diasdavid a test in `interface-stream-muxer` is timing out in browser runs, I wonder whats' the best way of handling it, increase it on the test itself or add a global timeout? Not sure if setting the timeout in the generic tests would be the right way to go?

**Comment by dryajov** [comment]
@diasdavid I've set the timeout globally for now, unless you want me to make the change on the interface tests them self.

**Comment by dryajov** [comment]
I'm currently getting 

```
  1) HTTP API
       ## interface-ipfs-core over ipfs-api
         .files
           .cat
             errors on unknown path:
     AssertionError: expected 'Failed to cat file: Error: No such file' to be one of [ Array(2) ]
      at ipfs.files.cat.catch (node_modules/interface-ipfs-core/src/files.js:439:36)
      at <anonymous>
      at process._tickDomainCallback (internal/process/next_tick.js:228:7)
```

when running test for js-ipfs locally. It happens for both, when linking this module or with nothing linked at all. I doubt it is related to this change, though.

**Comment by diasdavid** [comment]
> a test in interface-stream-muxer is timing out in browser runs

Increase in the test itself (as usual)

> https://github.com/libp2p/js-libp2p-multiplex/pull/70#issuecomment-351278998

Sounds good then :)

**Pull request merged**
